feat(question_ui): error handling
questionpy-org/questionpy-sdk pull request #121
Opened 2024-08-13 15:49 UTC by janbritz

Closes #118.

Zusätzlich wird bei XML Syntax Fehlern das Rendern fortgesetzt und eine Fehlermeldung auf der Seite angezeigt.

![image](https://github.com/user-attachments/assets/07e6d1fa-f43e-464d-80e2-045f7b4e15c6)

Jegliche Fehlermeldungen werden geloggt und im HTML angezeigt.

Die Fehlermeldungen werden folgendermaßen sortiert:
1. Syntax Fehler
2. Fehler in unbekannter Zeile
3. Zeile

Leider ist es nicht ohne Weiteres möglich bei qpy-Fehlern auch die betroffene Spalte in der XML auszugeben.
Auch bei der Zeilenangabe gibt es ein kleine Unschönheit:
```
<div xmlns="http://www.w3.org/1999/xhtml" xmlns:qpy="http://questionpy.org/ns/question">
    <span
        qpy:feedback="unknown"
    >Unknown feedback type.</span>
</div>
```
Hier ist ein Fehler in Zeile 3, ausgegeben wird aber Zeile 4, da dort das `>` ist. Das kann auch nicht ohne Weiteres gefixt werden.

2024-08-19 13:46 UTC, MHajoha requested changes

2024-08-19 13:46 UTC, MHajoha commented on questionpy_sdk/webserver/attempt.py
> +        context["render_errors"]["General Feedback"] = renderer.errors
Eine Property abhängig vom side effect einer anderen Property zu machen halte ich für kein gutes Design. Ich verstehe eh nicht so recht, warum `html` eine Property ist statt einer Methode `render() -> (str, RenderErrorCollection)`, aber in jedem Fall sollte der Wert von `errors` unabhängig davon sein, ob vorher `html` abgefragt wurde. (Und Properties sollten mMn nie nach außen sichtbare side effects haben)

2024-08-19 13:46 UTC, MHajoha commented on questionpy_sdk/webserver/question_ui/errors.py
> +        return html.escape(self.message)
1. Ob eine Property gecached oder jedes mal neu berechnet wird ist ein Implementierungsdetail und kein Teil der API. Bei den `@abstractmethod`s ist hat `@cached_property` also nichts zu suchen, lieber einfach `@property`.
2. (Das gilt für die ganze Datei) Lasst uns `@cached_property` bitte wirklich nur für teure Sachen verwenden. Einmal hat das Ding Overhead, der [definitiv weit größer](https://github.com/python/cpython/blob/main/Lib/functools.py#L1023) ist als `self.line or 0`, und auch wenn es den nicht hätte, ist es hier einfach nicht nötig und macht nur Noise. Ich finde keine der neuen `@cached_property` berechtigt.

2024-08-19 13:46 UTC, MHajoha commented on questionpy_sdk/webserver/templates/attempt.html.jinja2
> +            </table>
Macht es das CSS nicht unnötig kompliziert, alle Sektionen in eine Tabelle zu gießen und die Überschriften so zu stylen als seien sie keine Tabellenzeilen? Wäre es nicht einfacher, tatsächlich separate Tabellen zu machen?

2024-08-19 13:46 UTC, MHajoha commented on tests/questionpy_sdk/webserver/test_question_ui.py
> +            "Shuffled order should remain consistent across renderings with " "the same seed"
```suggestion
            "Shuffled order should remain consistent across renderings with the same seed"
```

2024-08-19 13:46 UTC, MHajoha commented on tests/questionpy_sdk/webserver/test_question_ui.py
> +        assert message.match(actual_error.html_message) is not None
Vielleicht ein Fall für `zip` bzw. `zip_longest`?

2024-08-20 13:44 UTC, janbritz commented on questionpy_sdk/webserver/templates/attempt.html.jinja2
> +            </table>
Es braucht etwas mehr CSS, aber unnötig ist es mMn nicht, da dadurch die "Line"-Spalte in allen `<tbody>`s gleich breit bleibt und die UI sauberer aussieht.

2024-08-21 12:16 UTC, MHajoha approved these changes

2024-08-28 15:27 UTC, MartinGauk approved these changes

2024-09-17 12:28 UTC, merged