fix: formulation template name
questionpy-org/questionpy-sdk pull request #132
Opened 2024-10-29 12:13 UTC by janbritz

Fixes #130.

2024-10-29 18:08 UTC, larsbonczek reviewed
Ich bin mir nicht sicher, ob es sinnvoll ist, das so zu lösen. Das minimal example soll ja als Orientierung für Paketentwickler*innen dienen. Aber ist das mit diesen automatisch berechneten Konstanten wirklich das, was wir als Standard-Vorgehen im QuestionPy-Ökosystem sehen wollen? Ich denke es wäre besser wenn entweder

- der Namespace und Kurzname beim Erzeugen des Beispiel-Pakets in der entsprechenden Zeile eingefügt werden (das klappt im Manifest ja auch), oder
- die `get_template`-Funktion ohne Angabe des Namespace und Kurznamen aufgerufen werden kann und dann per Default im Template-Verzeichnis des eigenen Pakets sucht.

2024-10-31 17:36 UTC, tumidi commented on questionpy_sdk/commands/create.py
> +            if file.filelineno() == 20:  # noqa: PLR2004
Die Zeilennr. hardcoden kann's irgendwie nicht sein. Das geht kaputt sobald jemand die Datei mal anfassen muss.

2024-10-31 17:39 UTC, tumidi commented
Meine 2 Cents zu dem Thema: Ich würde ja das *project scaffolding* komplett von den examples trennen. Dafür gibt's ja eigentlich ganz gute Lösungen: z.B. [Cookiecutter](https://github.com/cookiecutter/cookiecutter). Da schreibt man letztendlich jinja2-Templates.

- Da programmatisch die Zip-Datei zu entpacken und text replacement auf Zeilenebene zu machen ist im besten Fall hacky, geht aber spätestens dann kaputt wenn jemand das nächste Mal die Datei `question_type.py` editiert.
- Den Hack mit `build.py` und `minimal_example.zip` wären wir dann auch endlich los.
- Ließe sich btw auch unabhängig vom SDK verwenden: `pipx run cookiecutter gh:questionpy-org/cookiecutter-foo`
- Im SDK würde das`create`-Kommando intern die Cookiecutter-Python-API nutzen.

2024-11-01 10:16 UTC, larsbonczek requested changes

2024-11-01 10:16 UTC, larsbonczek commented on questionpy_sdk/commands/create.py
> +            if file.filelineno() == 20:  # noqa: PLR2004
Sehe ich auch so.

2024-12-05 12:00 UTC, janbritz commented
Siehe:
- #136
- #139

2024-12-05 12:00 UTC, closed without merging