SDK: Webserver soll Options aus dem Browser auswerten
questionpy-org/questionpy-sdk pull request #39
Opened 2023-04-18 14:23 UTC by alexanderschmitz

Daten aus der Options Form sollen beim Klicken auf den _Save Changes_ Button an den Server geschickt werden.

Zusätzlich sollen die Änderungen aus #37 und #33 in den Jinja Templates und dem lokalen Testserver übernommen werden.

Closes #26

2023-05-15 13:17 UTC, MHajoha requested changes

2023-05-15 13:17 UTC, MHajoha commented on example/python/local/example/main.py
> +    None
Warum `None` statt `pass`?

2023-05-15 13:17 UTC, MHajoha commented on questionpy_sdk/webserver/app.py
>      }
Wollen wir hier nicht eher den State abspeichern und in `get_options_form` stecken, wie das auch in echt passieren würde?

2023-05-15 13:17 UTC, MHajoha commented on questionpy_sdk/webserver/static/script.js
> +        return response;
```suggestion
        return await fetch(url, {
            method: "POST",
            headers: headers,
            body: JSON.stringify(body)
        });
```

2023-05-16 07:12 UTC, alexanderschmitz commented on questionpy_sdk/webserver/app.py
>      }
Meinst du in `submit_form` einen neuen State erstellen mit `create_question_from_options` und den State dann speichern?

2023-05-16 07:14 UTC, alexanderschmitz commented on example/python/local/example/main.py
> +    None
Ich hatte mal einen Error, den ich damit losgeworden bin, kann das aber nicht mehr reproduzieren. Ich nehms raus.

2023-05-16 07:16 UTC, janbritz requested changes

2023-05-16 07:16 UTC, janbritz commented on questionpy_sdk/webserver/form_storage.py
> +        json.dump(form_data, open(path, 'w'))
Hier und in `get()` müssten noch `close()` aufgerufen werden, am besten direkt über einen Kontextmanager:

```suggestion
        with path.open('w') as file:
            json.dump(form_data, file)
```

2023-05-16 07:16 UTC, janbritz commented on questionpy_sdk/webserver/form_storage.py
> +        return json.loads(open(path).read())
Man kann auch direkt die `.read_text()` Methode aufrufen, dann spart man sich den Kontextmanager:
```suggestion
        return json.loads(path.read_text())
```

2023-05-16 09:30 UTC, MHajoha commented on questionpy_sdk/webserver/app.py
>      }
Genau. Also ich glaube du meinst das richtige.

Das LMS, dessen Rolle du hier spielst, schickt die Form-Daten an den QuestionPy-Server (hier eben direkt `create_question_from_options`), um daraus den Question State zu generieren. Der wird dann abgespeichert (aber nicht verarbeitet). Beim Laden der Form wird der Question State dann mitgeschickt, und neben der Form-Definition kommen auch die aktuellen Form-Daten raus.

2023-05-16 11:04 UTC, alexanderschmitz commented on questionpy_sdk/webserver/app.py
>      }
Ok können wir so machen. Wenn ich das richtig verstehe muss ich dann im `example` package in der Klasse `ExampleQuestionType` Funktionen aus der Superklasse implementieren.

2023-05-22 14:55 UTC, MHajoha commented on questionpy_sdk/webserver/app.py
>      }
Wie vorhin besprochen: Die Standard-Impls aus `QuestionType` sollten für das Beispiel reichen, aber Pakete können die Methoden auch überschreiben.

2023-06-05 10:49 UTC, MHajoha requested changes

2023-06-05 10:49 UTC, MHajoha commented on questionpy_sdk/webserver/state_storage.py
> +            return ""
Ich vermute, dass für HiddenElement, TextInputElement, CheckboxElement und RadioGroupElement hier keine Logik nötig ist. (habe das aber auch nicht ausprobiert) Das Paket bzw. SDK setzt sinnvolle Defaults für die Elemente. Sollte es Paket-seitig kein Default geben, wollen wir, dass im Paket ein Fehler geworfen wird, wenn das Feld nicht ausgefüllt wurde.

Für SelectElement, GroupElement und RepetitionElement müssen aus den flachen Form-Daten halt verschachtelte Listen bzw. Dicts gemacht werden, wie du das hier auch schon tust. Im Moodle-Plugin werden beim Rendern der Form sinnvolle Element-Namen gesetzt, wie z.B. `section[repetition][0][group][element]`. Das verhindert einerseits Namenskollisionen (die hier noch möglich sind) und macht es einfacher, danach verschachtelte Objekte daraus zu machen (PHP macht sogar das automatisch). Ich würde dir empfehlen, das hier ähnlich zu machen. (muss aber nicht unbedingt in diesem PR sein.)

Aus `section[repetition][0][group][element]` würde dann
```json
{
  "section": {
    "repetition": [
      {
        "group": {
          "element": "abc"
        }
      }
    ]
  }
}
```

2023-06-13 08:00 UTC, alexanderschmitz commented on questionpy_sdk/webserver/state_storage.py
> +            return ""
Ich hab die Änderungen, die wir gestern besprochen haben umgesetzt.

2023-06-13 09:00 UTC, MHajoha approved these changes

2023-06-13 09:00 UTC, MHajoha commented on questionpy_sdk/webserver/app.py
> +        form_definition, _ = await worker.get_options_form(None)
Es wäre wahrscheinlich sinnvoll, hier den zuletzt gespeicherten State zu laden. Vielleicht kannst du das ja noch (oder im nächsten PR) angehen. Ansonsten sieht alles gut aus :+1:

2023-06-15 07:33 UTC, janbritz approved these changes

2023-06-15 07:33 UTC, janbritz commented on example/python/local/example/main.py
> +
```suggestion
```
Diese Zeilen müssten gelöscht werden können.

2023-06-15 07:33 UTC, janbritz commented on questionpy_sdk/webserver/state_storage.py
> +        return options
```suggestion
        return self._parse_section(form_definition.general, form_data)
```

Da `_parse_section()` nur hier verwendet wird und nur das Ergebnis des Methodenaufrufs zurückgegeben wird, könnte man eigentlich direkt die Logik in `parse_form_data()` platzieren.

2023-06-15 07:33 UTC, janbritz commented on questionpy_sdk/webserver/state_storage.py
> +        if not path or not path.exists():
```suggestion
        if not path.exists():
```

2023-06-21 16:21 UTC, merged