Hifle Texte in der Optionform im SDK Webserver
questionpy-org/questionpy-sdk pull request #53
Opened 2023-08-08 11:23 UTC by alexanderschmitz

- Hilfetexte der `FormElemente` werden angezeigt, wenn man auf das Hilfe Icon neben des Labels klickt.
- Wenn man woanders hinklickt, verschwindet der Hilfetext. 
- Beim drüber-hovern wird ein kleines Feld angezeigt, wie in den Forms bei Moodle auch.

*das Icon habe ich selber mit Inkscape erstellt weil ich mir bei Lizensierung mit anderen Icon-Libraries unsicher war.

2023-08-10 11:43 UTC, MHajoha requested changes

2023-08-10 11:43 UTC, MHajoha commented on questionpy_sdk/webserver/static/styles.css
> +}
Ich kann keinen Unterschied erkennen, wenn ich diesen Block entferne (auf Firefox). Was macht das?

2023-08-10 11:43 UTC, MHajoha commented on questionpy_sdk/webserver/static/help_icon.png
Nettes Icon. Magst du noch das SVG committen, damit wir das in Zukunft falls nötig anpassen können?

2023-08-10 11:43 UTC, MHajoha commented on questionpy_sdk/webserver/static/styles.css
> +}
Falls du das selbst geschrieben hast: Magst du kurz in Kommentaren erklären, wie das funktioniert? (Also insb. das Zusammenspiel von `display: table` und den Transforms?
Falls das aus einem Blog-Post o.ä. kommt, bitte verlinken.

2023-08-10 11:43 UTC, MHajoha commented on questionpy_sdk/webserver/static/script.js
> +}
Die beiden müssen nicht async sein. (`delete_repetition_element` auch nicht, das sehe ich jetzt erst)

2023-08-14 06:51 UTC, alexanderschmitz commented on questionpy_sdk/webserver/static/help_icon.png
wo soll ich den Ordner dafür hinlegen?

2023-08-14 08:19 UTC, alexanderschmitz commented on questionpy_sdk/webserver/static/styles.css
> +}
Du hast recht! Das wird nicht gebraucht.

2023-08-14 08:24 UTC, MHajoha commented on questionpy_sdk/webserver/static/help_icon.png
Wie du magst. Du kannst es auch einfach in `questionpy_sdk/webserver/static/help_icon.svg`, also neben das PNG legen

2023-08-14 08:30 UTC, MartinGauk commented on questionpy_sdk/webserver/static/help_icon.png
Würde nicht nur das SVG auch ausreichen (also statt des PNG)?

2023-08-23 14:03 UTC, MHajoha approved these changes

2023-08-23 14:05 UTC, merged