Question UI
questionpy-org/questionpy-sdk pull request #73
Opened 2024-02-22 10:49 UTC by alexanderschmitz

# PR zur Fragenanzeige:

## QuestionUI Renderer Klasse

Ich habe probiert hier die Funktionalitäten des QuestionUI Renderers aus dem Moodle Plugin ([hier](https://github.com/questionpy-org/moodle-qtype_questionpy/blob/dev/classes/question_ui_renderer.php)) abzubilden.

Die `xml` Library fand ich nicht ausreichend daher wird `lxml` verwendet.

Hier sind noch einige Baustellen:

- Verschiedene Funktionen sind noch nicht implementiert (siehe TODOs in `render_part()`.
- mypy, pylint sind nicht so zufrieden mit `lxml`. Da gibt es einige Warnungen, die ich noch nicht beheben konnte.

## Anzeigen der Frage im Webserver

- Neue Routen im Webserver zum:
  -  Anzeigen der Frage mit GET `/question`
  - Anpassen der Display Options mit POST `/question`
- Neues jinja template 

Baustellen hier:
- Das xhtml vom Worker bekommen (aktuell hardcoded)
- Attempt Handling
- CSS

closes #67

2024-03-05 09:43 UTC, alexanderschmitz commented
Mir fällt noch ein, dass man selber zu `http://0.0.0.0:8080/attempt` navigieren muss um die Preview zu sehen. Man könnte noch einen Button von der Options Form zum Attempt einfügen, der auch erst nach dem submitten der Options Form angezeigt wird.

2024-03-07 11:50 UTC, MartinGauk commented
Das gefällt mir schon recht gut. Die Zustände sollten wir allerdings an einer anderen Stelle als dem Server speichern. Während einer Paketentwicklung will ich ja schon Fragen ausprobieren können, einen Bug oder so iterativ fixen und immer mal wieder abgeben können, ohne meine Antwort oder die Einstellungen neu eingeben zu müssen (weil ich das SDK neustarten muss).

Als eine Maßnahme, die sicherlich in diesem PR noch bis zum Code Freeze nächste Woche erledigt werden kann, könntest du den Zustand zu den "Display Options" in einem Cookie statt auf dem Server speichern. Du könntest per JS ein Cookie setzen und die Daten können dann vom Server gelesen werden.

2024-03-12 17:35 UTC, MHajoha requested changes
Sieht schon sehr gut aus :+1:

2024-03-12 17:35 UTC, MHajoha commented on questionpy_sdk/webserver/question_ui.py
> +    return query
Das finde ich ein wenig unschön, leider ist lxml ein Clusterfuck was die Typisierung betrifft
* "iterable" ist nicht das gleiche wie "list". Ein passenderer Name wäre `assert_list` oder `as_list`
* Weil der Rückgabewert `list` aka `list[Any]` ist, wird alles, was du mit den Elementen / Attributen in der Liste machst, nicht getypecheckt.

Da der Rückgabetyp mWn eindeutig durch den XPath-Ausdruck vorgegeben wird und der immer gehardcoded ist, fände ich es ausreichend, wenn du als Rückgabewert einfach `list[etree._Element]` (bzw. für Attribute dann `list[etree._AnySmartStr]`) behauptest bzw. castest.

2024-03-12 17:35 UTC, MHajoha commented on questionpy_sdk/webserver/question_ui.py
> +        self.required_fields: List[str] = []
```suggestion
        self.required_fields: list[str] = []
```

2024-03-12 17:35 UTC, MHajoha commented on questionpy_sdk/webserver/question_ui.py
> +        """
```suggestion
        """Extracts metadata from the question UI."""
```

2024-03-12 17:35 UTC, MHajoha commented on questionpy_sdk/webserver/question_ui.py
> +                                                 namespaces=namespaces):
Tut es hier nicht auch 
```suggestion
            for element in self.question.findall(f".//qpy:formulation//xhtml:{element_type}",
                                                 namespaces=namespaces):
```

2024-03-12 17:35 UTC, MHajoha commented on questionpy_sdk/webserver/question_ui.py
> +                formatted_str = f"{{:.{precision}f}}".format(float_val)
Müsste auch komplett im f-string gehen: `f"{float_val:.{precision}f}"`

2024-03-12 17:35 UTC, MHajoha commented on questionpy_sdk/webserver/app.py
> +    display_options = QuestionDisplayOptions(**json.loads(request.cookies.get('display_options', '{}')))
Hier (und an all den anderen Stellen) lieber `model_validate_json`

2024-03-12 17:35 UTC, MHajoha commented on questionpy_sdk/webserver/question_ui.py
> +        """
Argument-Typen würdest du im Docstring mit `attempt (Optional[dict]): Beschreibung` angeben. Das ist aber gar nicht nötig (oder hilfreich), wenn eh die Signatur getypehinted ist.

```suggestion
        """Renders the contents of the `qpy:general-feedback` element or returns `None` if there is none."""
```

2024-03-13 15:21 UTC, MHajoha requested changes

2024-03-13 15:21 UTC, MHajoha commented on questionpy_sdk/webserver/question_ui.py
> +                                                           namespaces={'qpy': "http://questionpy.org/ns/question"})):
Lieber hier auch die Konstanten verwenden (+ an ein paar anderen Stellen)

2024-03-13 15:21 UTC, MHajoha commented on questionpy_sdk/webserver/question_ui.py
> +    return list[etree._Element](query)
Ist das Kopieren hier nötig?

2024-03-13 15:21 UTC, MHajoha commented on questionpy_sdk/webserver/app.py
> +    return response
Nach genauerer Überlegung finde ich den Datenfluss hier doch etwas komisch.
* Gibt es einen Grund, dass die Daten an der `WebServer`-Instanz gespeichert werden? Wenn sie per Cookie an den nächsten Request weitergegeben werden, ist das doch nicht nötig?
* Dass hier nur `start_attempt` und `score_attempt` abgedeckt werden, finde ich nicht optimal. Wir sollten auch `get_attempt` abdecken, sowohl für einen gestarteten, aber noch nicht bewerteten, Attempt, als auch für einen schon bewerteten.

  Ideal wäre auch eine Save-but-don't-submit Aktion, wie in Moodle.
  
  Ich würde vorschlagen, in Cookies nur attempt state und score (inkl. scoring state) abzuspeichern, und dann vorm Rendern `get_attempt` falls nötig aufzurufen, um an das `AttemptModel` zu kommen. So ist es auch im Plugin (naja, bisher minus scoring state)

2024-03-13 15:21 UTC, MHajoha commented on questionpy_sdk/webserver/app.py
> +    response = web.json_response(status=201, text='Attempt submitted.')
Hier baust du eine Response mit `Content-Type: application/json` aber Inhalt `Attempt submitted.` zusammen (was offensichtlich kein JSON ist). Wenn du die Antwort nicht weiter verwendest kannst du denke ich einfach eine leere Antwort nehmen.

2024-03-18 15:03 UTC, MHajoha approved these changes
Mir fällt gerade auf, dass der Score noch gar nicht angezeigt wird. Das wäre noch mega. Also `ScoreModel.scoring_code` und `ScoreModel.score`. Bei `classification` ist die Bedeutung glaube ich noch nicht 100% klar, das kann also gern draußen bleiben.

Ansonsten danke für's schnelle Umsetzen :+1:

2024-03-18 15:30 UTC, MHajoha requested changes

2024-03-18 15:30 UTC, MHajoha commented on questionpy_sdk/webserver/question_ui.py
> +        return self.render_part(elements[0], attempt, options)
Fällt mir spät auf: Hat eine Frage mindestens einen dieser Teil nicht, fliegt hier ein `IndexError`, wo du aber vermutlich `None` zurückgeben willst.

2024-03-18 15:59 UTC, MartinGauk commented
Scores brauchen wir natürlich auch noch, aber das kann in einen nächsten PR. :)

2024-03-18 18:22 UTC, MHajoha requested changes
Entschuldige dass das so Häppchenweise kommt, ich versuche gerade, die Beispielpakete damit auszuführen

2024-03-18 18:22 UTC, MHajoha commented on questionpy_sdk/webserver/templates/attempt.html.jinja2
> +        <button id="edit-attempt-button" data-route="/attempt/edit" {% if not form_disabled %}disabled{% endif %}>Edit</button>
Die beiden Kollegen submitten die Form auf normalem Wege, noch bevor der Fetch-Request fertig gesendet wird. (Die Erkenntnis hat viel debugging gekostet :smile:). Als Lösung `type="button"` (was kein Default-Behaviour mit sich bringt) oder `event.preventDefault()` (oder beides).

2024-03-19 07:37 UTC, alexanderschmitz commented
> Entschuldige dass das so Häppchenweise kommt, ich versuche gerade, die Beispielpakete damit auszuführen

Alles gut. Ich hab das nur mit dem einen Example Paket ausprobiert.

2024-03-19 07:40 UTC, alexanderschmitz commented on questionpy_sdk/webserver/templates/attempt.html.jinja2
> +        <button id="edit-attempt-button" data-route="/attempt/edit" {% if not form_disabled %}disabled{% endif %}>Edit</button>
Ok damit hab ich nicht gerechnet, dass der default Typ für einen button `submit` ist und nicht `button` ist.

2024-03-19 10:15 UTC, MHajoha commented on questionpy_sdk/webserver/templates/attempt.html.jinja2
> +        <button id="edit-attempt-button" data-route="/attempt/edit" {% if not form_disabled %}disabled{% endif %}>Edit</button>
Das wäre ja auch zu einfach :laughing:

2024-03-19 13:01 UTC, MHajoha approved these changes
Ich glaube hier ist squashen angebracht ^^

2024-03-19 13:12 UTC, merged