Neue Route zum Abrufen statischer Dateien
questionpy-org/questionpy-sdk pull request #95
Opened 2024-05-31 10:41 UTC by larsbonczek

Die URL enthält nicht den Paket-Hash, da dieser nicht immer bekannt ist (wenn ein Ordner direkt ausgeführt wird). Dafür wird ein no-cache Header übermittelt (der Paket-Hash hätte sonst für das Cache-busting gesorgt).

Closes #87

2024-05-31 14:49 UTC, tumidi requested changes

2024-05-31 14:49 UTC, tumidi commented on questionpy_sdk/webserver/routes/worker.py
> +    worker: Worker
Warum deklarieren wir nochmal `worker` vor dem `with`? Machen wir auch an vielen anderen Stellen, aber die Sinnhaftigkeit entzieht sich mir aktuell.

2024-05-31 14:49 UTC, tumidi commented on questionpy_sdk/webserver/routes/worker.py
> +    worker: Worker
Evtl. direkt hier diskutieren:
https://github.com/questionpy-org/questionpy-sdk/pull/97
https://github.com/questionpy-org/questionpy-server/pull/100

2024-05-31 16:01 UTC, tumidi commented on questionpy_sdk/webserver/routes/worker.py
> +    worker: Worker
https://github.com/questionpy-org/questionpy-sdk/pull/97#issuecomment-2142547245

2024-05-31 16:02 UTC, tumidi approved these changes

2024-06-13 09:52 UTC, MartinGauk approved these changes

2024-06-13 09:52 UTC, merged